"""Generates ``reports/engine_reconciliation.md``. SPEC.md 7.4, W5-P3.

Runs :func:`mafrm.backtest.reconciliation.reconciliation` -- the synthetic
panel first, then the real cache -- and writes the comparison table with the
bound, the verdict per row and the attribution of the one row that is expected
to breach. Exits non-zero if any row is not as registered, and still writes the
report: a discrepancy is a finding, and it goes in the table rather than being
smoothed over.
"""

from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path

import numpy as np

from mafrm import config as config_mod
from mafrm.backtest import reconciliation as rec

__all__ = ["main", "render", "report_path"]

_BPS = 1e-4


def report_path() -> Path:
    return config_mod._REPO_ROOT / "reports" / "engine_reconciliation.md"


def _fmt_nav(value: float) -> str:
    return f"{value:,.6f}"


def _row(row: rec.Comparison) -> str:
    verdict = "as registered" if row.as_expected else "**NOT AS REGISTERED**"
    within = "within" if row.within_tolerance else "exceeds"
    return (
        f"| {row.label} | {row.fee_financing} | {row.half_spread / _BPS:.2f} | {row.steps} | "
        f"{_fmt_nav(float(row.reference.iloc[-1]))} | {_fmt_nav(float(row.comparand.iloc[-1]))} | "
        f"{row.max_abs_gap:.3e} | {row.tolerance:.3e} | {row.gap_over_tolerance:.3g} | "
        f"{row.annualised_gap_bps:+.4f} | {row.expectation} | {within}, {verdict} |"
    )


def render(result: rec.Reconciliation, cfg: config_mod.Config | None = None) -> str:
    cfg = cfg or config_mod.load()
    costs = cfg.model.costs
    rules = cfg.model.backtest.reconciliation
    eps = float(np.finfo(np.float64).eps)
    panels = {row.panel: row for row in result.rows}
    lines: list[str] = []
    w = lines.append

    w("# Engine reconciliation against `bt` (SPEC.md 7.4) -- W5-P3")
    w("")
    w("Generated by `python -m mafrm.backtest.reconciliation_report`.")
    w(
        f"Comparand: `bt` {metadata.version('bt')} (`ffn` {metadata.version('ffn')}), MIT, dev extra only."
    )
    w("")
    w("## 1. What is reconciled here, and what is not")
    w("")
    w(
        '`bt` models a proportional commission and nothing else. It therefore reconciles the **accounting** -- units, cash, valuation, drift between rebalances, rebalancing on given dates -- and the **spread term** of SPEC.md 7.1 as a proportional cost. **It cannot reconcile the impact term.** The cross-check is complete in two halves: the impact term was reconciled against the SPEC.md 7.1 formula by W5-P1\'s hand-computed tests (`tests/test_impact.py`, each term at three trade sizes in both regimes), and `bt` covers what it models (operator ruling 3, 2026-09-03). "Reconciled against `bt`" in this project never means the whole cost function.'
    )
    w("")
    w(
        "Why this table exists: Yin et al. (2026), *alphaXiv 2603.20319*, ran identical strategy logic through mainstream backtest engines and found divergence of up to **3.71%** for high-turnover rotation strategies, from implementation differences alone -- including a silent division error in a production cost model. That is the case for a transparent engine tested line by line (`tests/test_engine.py`, every value by hand) and for this cross-check."
    )
    w("")
    w("## 2. The three conventions held fixed, so that accounting is what gets tested")
    w("")
    w(
        "1. **Dates.** Both engines rebalance on `mafrm.data.calendar.month_end_dates` of the same panel -- the project's one definition of month end. `bt` is FED those dates (`RunOnDate` + `WeighTarget`) and never resamples its own month ends (operator ruling 2; CLAUDE.md failure mode 1)."
    )
    w(
        "2. **Prices.** Both engines see the same total-return index, built once by `mafrm.data.prices.total_return` from raw closes and the ex-date dividend table. Dividend accounting is therefore the project's (W1) and is not what `bt` checks."
    )
    w(
        f"3. **Fee financing.** The engine hits the target dollar positions on `NAV_pre` and debits the cost from cash. `bt`'s native commission is absorbed into the trade by `SecurityBase.allocate`'s fixed point, so the target is missed by the fee and cash stays flat. Both are run. The *cash-financed* rows give `bt` the engine's convention through a two-line algo that debits `a x |outlay|` after `Rebalance` -- the same kind of alignment as feeding it the dates. The *native* rows keep the convention gap visible and **attribute** it: a shadow replay of `bt`'s fee-absorbing fixed point on the engine's own arithmetic, iterated to `bt`'s own stopping rule (`numpy.isclose`, `atol` {rec._bt_absolute_stop():.0e}), must agree with `bt` to the bound."
    )
    w("")
    w("## 3. The bound")
    w("")
    w(
        f"`c x eps x T` relative on NAV, `c = 2 x (assets + {rules.accounting_roundings})`, `eps = {eps:.3e}`, `T` the number of daily accounting steps (operator ruling 1; `config/model.yaml` `backtest.reconciliation`, where the eight roundings are counted). The same construction as `numerics.psd_reconstruction_roundings`: set by representation and accumulation length, not by what needed to clear. A discrepancy above it is attributed to a named cause or it is a bug in one of the two engines. It is never widened. `gap / bound` is reported the way `reports/psd_repairs.md` reports its margin in ulps."
    )
    w("")
    for panel, sample in panels.items():
        w(
            f"- **{panel}**: {sample.assets} assets, `c` = {rules.coefficient(sample.assets)}, `T` = {sample.steps}, bound = {sample.tolerance:.3e}; "
            f"{sample.reference.index[0].date()} to {sample.reference.index[-1].date()}; assets {', '.join(sample.asset_names)}."
        )
    w("")
    w("## 4. The comparison table")
    w("")
    w(
        f"Initial NAV {rules.initial_nav:,.0f} in both engines (`bt`'s own default; it cancels in every ratio). Half-spread `a` = `costs.flat_spread_assumption_bps / 2` = {costs.flat_spread_assumption_bps / 2:.2f}bp, SPEC.md 7.1's `a_i` for the flat 5bp strawman; both engines receive the same rate, so every verdict is invariant to it. Fractional units in both. Reference is the engine except on the shadow rows, where it is the replay; comparand is `bt`."
    )
    w("")
    w(
        "| Row | Fee financing | `a` (bp) | `T` | Final NAV, reference | Final NAV, `bt` | max abs gap | bound | gap / bound | annualised gap (bp/yr) | expected | verdict |"
    )
    w("|---|---|---|---|---|---|---|---|---|---|---|---|")
    for row in result.rows:
        w(_row(row))
    w("")
    w(
        "`expected = within` rows are the reconciliation proper and must pass. `expected = exceeds` rows are the fee-financing convention gap, expected to breach the bound because it is a convention and not noise; the shadow row beneath each attributes it."
    )
    w("")
    w("## 5. Attribution of the native-commission rows")
    w("")
    native = [row for row in result.rows if row.expectation == "exceeds"]
    shadows = [row for row in result.rows if "shadow" in row.label]
    for gap_row, shadow_row in zip(native, shadows, strict=True):
        status = (
            "attributed in full"
            if shadow_row.within_tolerance
            else "**UNATTRIBUTED -- a bug in one of the two engines**"
        )
        w(
            f"- **{gap_row.panel}.** Engine vs `bt` native: max gap {gap_row.max_abs_gap:.3e} of NAV, {gap_row.gap_over_tolerance:.3g}x the bound, {gap_row.annualised_gap_bps:+.4f} bp/yr annualised. "
            f"Named cause: fee financing (target missed by the fee, cash flat) and commission on the units actually traded rather than on the intended notional. "
            f"Shadow replay vs `bt` native: max gap {shadow_row.max_abs_gap:.3e}, {shadow_row.gap_over_tolerance:.3g}x the bound -- {status}."
        )
    w("")
    w(
        "The convention gap is the fee's own return: at 2.5bp on monthly turnover of a few percent the fee is of order 1e-6 of NAV per rebalance, and what differs between the conventions is only where that 1e-6 sits (in the risky book or in cash) until the next rebalance. It is real, it is small, and it is not a disagreement about accounting."
    )
    w("")
    w("## 6. Caveats, carried")
    w("")
    w(
        "- The five curve points are traded through their SPEC.md 7.1.1 proxies (SHY, IEI, IEF, TLT, TIP); TLT is roughly half a 30y zero's duration. This is an accounting check on the proxies' total-return indices; no cost figure here is a cost of trading the exposure the risk model priced."
    )
    w(
        "- The proportional rate is the flat strawman's half-spread, used only because both engines must receive the same number. No issuer level, EDGE shape or impact enters this table; the cost model proper is `reports/cost_calibration.md`."
    )
    w(
        "- In-sample only. Every read goes through `mafrm.data.cache.read`, which stops strictly before `sample.holdout_start`, and the panel is aligned with the boundary as its half-open upper bound."
    )
    w(
        "- Equal weight on the real panel is the absence of a choice, not a strategy; no Sharpe is reported and nothing here reaches a model. experiments.md rows 199-206, all `data-diagnostic`."
    )
    w("")
    overall = (
        "ALL ROWS AS REGISTERED"
        if result.all_as_expected
        else "AT LEAST ONE ROW IS NOT AS REGISTERED -- see the table"
    )
    w(f"**Outcome: {overall}.**")
    w("")
    return "\n".join(lines) + "\n"


def main() -> int:
    cfg = config_mod.load()
    result = rec.reconciliation(cfg, include_real=True)
    path = report_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    text = render(result, cfg)
    path.write_text(text, encoding="utf-8")
    for row in result.rows:
        flag = "ok " if row.as_expected else "BAD"
        print(
            f"{flag} {row.label}: gap {row.max_abs_gap:.3e} bound {row.tolerance:.3e} "
            f"({row.gap_over_tolerance:.3g}x) ann {row.annualised_gap_bps:+.4f} bp/yr"
        )
    print(f"wrote {path}")
    return 0 if result.all_as_expected else 1


if __name__ == "__main__":
    sys.exit(main())
